# Generated by Django 3.1.5 on 2021-04-29 19:13

from django.db import migrations
import django_countries.fields
import dl.models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_auto_20210429_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='country',
            field=django_countries.fields.CountryField(countries=dl.models.NACountries, max_length=2),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='shipping_country',
            field=django_countries.fields.CountryField(countries=dl.models.NACountries, default='CA', max_length=2),
        ),
    ]
