# Generated by Django 3.1.5 on 2021-05-01 20:09

from django.db import migrations
import django_countries.fields
import dl.models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_auto_20210429_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='country',
            field=django_countries.fields.CountryField(countries=dl.models.G8Countries, max_length=2),
        ),
    ]
