# Generated by Django 3.1.5 on 2021-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0007_auto_20210506_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
